name: "tieba"
mode: "dev"
port: 8888
version: "v1.0"
Start_time: "2022-04-23"
machineID: 1


log:
  level: "debug"
  filename: "tieba.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root"
  db_name: "tieba"
  mysql.max_open_conns: 200
  mysql.max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100

kafka:
  brokers:
    - "127.0.0.1:9092"
  group_id: "post-job"
  topic: "tieba_post"

elasticsearch:
  addresses:
    - "http://localhost:9200"
  index: "post"